version: "3"
services:
 phala-node:
   image: ${NODE_IMAGE}
   container_name: phala-node
   hostname: phala-node
   ports:
     - "9933:9933"
     - "9934:9934"
     - "9944:9944"
     - "9945:9945"
     - "30333:30333"
     - "30334:30334"
   environment:
     - NODE_NAME=${NODE_NAME}
     - NODE_ROLE=MINER
   volumes:
     - ${NODE_VOLUMES}

 phala-pruntime:
   image: ${PRUNTIME_IMAGE}
   container_name: phala-pruntime
   hostname: phala-pruntime
   ports:
     - "8000:8000"
   devices:
   
   environment:
     - EXTRA_OPTS=--cores=${CORES}
     - ROCKET_ADDRESS=0.0.0.0

 phala-pherry:
   image: ${PHERRY_IMAGE}
   container_name: phala-pherry
   hostname: phala-pherry
   depends_on:
     - phala-node
     - phala-pruntime
   restart: always
   entrypoint:
     [
       "/root/pherry",
       "-r",
       "--parachain",
       "--mnemonic=${MNEMONIC}",
       "--substrate-ws-endpoint=ws://phala-node:9945",
       "--collator-ws-endpoint=ws://phala-node:9944",
       "--pruntime-endpoint=http://phala-pruntime:8000",
       "--operator=${OPERATOR}",
     ]
